### ISSUE TITLE
Can't Pull hypriot/rpi-* Images: dial unix /var/run/docker.sock: no such file or directory 

### ISSUE THREAD

**Issue by packet-rat** [hypriot/rpi-python#1]
So just got my PI 2 1GB after reading what you folks have been up to with Docker on the Raspberry PI.
- Downloaded hypriot-rpi-20150329-140334.img
- Flashed to the SD

```
sudo dd if=hypriot-rpi-20150329-140334.img of=/dev/disk2 bs=2m
Password:
610+1 records in
610+1 records out
1280000000 bytes transferred in 876.009959 secs (1461171 bytes/sec)
```
- Unmounted the SD card, inserted in the PI 2 1GB, powered up, and logged in.

```
Linux black-pearl 3.18.10-hypriotos-v7+ #2 SMP PREEMPT Sun Mar 29 13:13:41 UTC 2015 armv7l
<SNIP>
HypriotOS: root@black-pearl in ~
$ docker pull hypriot/rpi-python
FATA[0000] Post http:///var/run/docker.sock/v1.17/images/create?fromImage=hypriot%2Frpi-python%3Alatest: dial unix /var/run/docker.sock: no such file or directory 
HypriotOS: root@black-pearl in ~
```

I verified external network connectivity and then tried pulling each of the hypriot/rpi-xxx files with the same outcome.

As far as I can tell, I followed all of the instructions verbatim but obviously missed something(?)

**Comment by StefanScherer** [comment]
Please check the docker daemon and restart it. Sometimes on first boot the docker daemon does not start automatically.

Just do a 

``` bash
sudo service docker restart
```

And try again.

**Comment by StefanScherer** [comment]
Please use official python images as they are multi-arch now and work on ARM.
