### ISSUE TITLE
rpi-python images missing "onbulid" target

### ISSUE THREAD

**Issue by vielmetti** [hypriot/rpi-python#2]
The official Docker python images have an "onbuild" target that is used to tackle the common task of installing prerequisites from a requirements.txt file. I'm trying to figure out how to reverse engineer that behavior into a Dockerfile, either to write that up for this image, or simply to adapt the instructions from

https://registry.hub.docker.com/u/library/python/

so taht the hypriot/rpi-python:onbuild target can exist.

**Comment by StefanScherer** [comment]
@vielmetti This should be pretty the same as the upstream Dockerfile. Normally just adjust the FROM line to build from the rpi-python image.

**Comment by StefanScherer** [comment]
Please use official python images as they are multi-arch now and work on ARM.
