### ISSUE TITLE
Clarify why to use this image

### ISSUE THREAD

**Issue by iBobik** [hypriot/rpi-python#3]
What is this image good for in comparison with other images like [official python](https://hub.docker.com/_/python/)?

Official image is well maintained (with autobuild) and offers great selection of tags (versions).
What offers this image?

**Comment by StefanScherer** [comment]
@iBobik The official python docker images are for Intel/AMD CPU's only. This rpi-python image is for ARM CPU's like the one on a Raspberry Pi and similar boards.

Where do you have missed this information as it is both in the README here in this repo as well as in the description at Docker Hub. So we could improve this.

**Comment by iBobik** [comment]
There is just:

> Raspberry Pi compatible Docker base image with Python preinstalled.

It don't mention official Python image will not work on RPi (and other ARM machines), so I did not saw reason why not use it.

Jan Pobořil
http://honza.poboril.cz/
1. 1. 2016 v 21:03, Stefan Scherer notifications@github.com:

**Comment by StefanScherer** [comment]
Please use official python images as they are multi-arch now and work on ARM.
