### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by phillipgreenii** [hypriot/rpi-python#4]
What would it take to add support for python 3?

**Comment by Govinda-Fichtner** [comment]
@phillipgreenii I guess just a PR. :)

**Comment by phillipgreenii** [comment]
Would you want python 3 in this repo or should there be a rpi-python3?  I'm not sure how you guys would want to continue supporting both 2.x and 3.x.

**Comment by firecyberice** [comment]
I just prepared a matrix build for both (python 2 and 3) in the python-3.5 branch but maybe the Dockerfiles need some fixes.

**Comment by StefanScherer** [comment]
Please use official python images as they are multi-arch now and work on ARM.
