### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by cp2587** [hypriot/rpi-python#5]
Hello,

Thank you very much for your work on docker for ARM plateform, it is precious :)

I tried using this image to build a python project, but i cannot find a way to install the requirements... Here is my dockerfile that returns "exec user process caused "exec format error"" when i am running the build (i am running the build command on my dev PC which is not ARM of course)

COPY requirements.txt requirements.txt
RUN ["pip", "install", ""--no-cache-dir", "-r", "requirements.txt"]

COPY src ./

EDIT: when build on my raspberry, it works. I guess you must build your image on the same environnement you will want your container to run ? There is no way to build this image on a non-ARM plateform ?

**Comment by StefanScherer** [comment]
Please use official python images as they are multi-arch now and work on ARM.
